platform :ios, '11.0'
use_frameworks!
workspace 'ReSwiftConsumer'

def common_pods
    pod 'ReSwift'
    pod 'ReSwiftConsumer', :path => '../'
end

target 'ReSwiftConsumer-iOS' do
  common_pods
#  target 'ReSwiftConsumer-iOSTests' do
#    inherit! :search_paths
#  end
end
