platform :ios, '10.3'
use_frameworks!

target 'ReSwiftConsumer-iOS' do
  pod 'ReSwift'
  pod 'ReSwiftConsumer', :path => '../'

  # target 'ReSwiftConsumer-iOSTests' do
  #   inherit! :search_paths
  # end
end
