# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode9.2

notifications:
  email:
    - hansune@me.com

branches:
  except:
    - gh-pages

install:
  - gem install xcpretty

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="ReSwiftConsumer"
    - UPDATE_DOCS="false"

matrix:
  include:
#   - env: SCHEME="macOS"  SDK="macosx10.13"          DESTINATION="arch=x86_64"                    SWIFT_VERSION="4.0"
    - env: SCHEME="iOS"    SDK="iphonesimulator11.0"  DESTINATION="OS=11.0,name=iPhone 8"          SWIFT_VERSION="4.0"
#   - env: SCHEME="tvOS"   SDK="appletvsimulator11.0"  DESTINATION="OS=11.0,name=Apple TV 1080p"   SWIFT_VERSION="4.0"


# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild 
    -workspace Example/ReSwiftConsumer.xcworkspace 
    -scheme "$FRAMEWORK_NAME-$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug

    ONLY_ACTIVE_ARCH=YES
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    SWIFT_VERSION=$SWIFT_VERSION
    test

#   after_success:
#     - bash <(curl -s https://codecov.io/bash) -J ReSwiftConsumer
#     - test $TRAVIS_PULL_REQUEST == "false" &&
#       test $TRAVIS_BRANCH == "master" &&
#       test $UPDATE_DOCS == "true" &&
#       .scripts/update-gh-pages


# script:
# - set -o pipefail 
# - xcodebuild -version
# - xcodebuild -showsdks
# - xcodebuild test -enableCodeCoverage YES -workspace Example/ReSwiftConsumer.xcworkspace -scheme ReSwiftConsumer-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint


